### ISSUE TITLE
Implementation guide package in Advanced Options is not loading

### ISSUE THREAD

**Issue by IndicinaAdmin** [inferno-community/fhir-validator-app#111]
Its been a few days and the advanced options IG packages are not loading. In addition, when running a validation on a resource instance that includes the profile structure definition in the meta or an extension, Inferno cannot resolve the definition or extension canonical URL. It validates against the base specification correctly though..

Patient.meta.profile[0]: Canonical URL 'http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient' does not resolve on line 6. [Jump to error.](https://inferno.healthit.gov/validator/results#error-6)
Patient.extension[0]: Unknown extension http://hl7.org/fhir/us/core/StructureDefinition/us-core-race on line 14. [Jump to error.](https://inferno.healthit.gov/validator/results#error-14)

**Comment by dehall** [comment]
Hi @michaelecampbell and @sathamneh , thanks for reporting this. 
The list of IGs in that dropdown comes from the public FHIR package server ( https://packages2.fhir.org/packages/catalog ) and it looks like there's an incorrectly formatted item in there now which is causing this problem. We're hoping that item can be fixed on the server quickly. If not then we'll need to make a code change to not crash, which will probably take a few days unfortunately. 

I've raised this issue on the FHIR Zulip, will keep you posted once we know more.

**Comment by dehall** [comment]
The issue with the package server was corrected overnight and I now see the IG list loading in the validator again, so I'm going to close this issue. (You may need to refresh the page if it's been open.) Please feel free to re-open if you're still seeing a problem
