### ISSUE TITLE
Loinc code validation issue

### ISSUE THREAD

**Issue by JuliusSkrisa** [inferno-community/fhir-validator-app#44]
Hi, firstly thank you for this validator, its really helpful!

I have a question regarding Loinc code validations.
It seems that something has changed recently and I am getting this error on the same FHIR that was ok few days ago.
Just wanted to confirm that it isn't an issue on the side of the validator. From my view it looks like the validator cannot validate the code for some reason?

Bundle.entry[5].resource.ofType(Observation).code.coding[0]: Error performing operation 'validate-code' with parameters for 'http://loinc.org#72831-1' on line 165. Jump to error.

```
  "code":{
     "coding":[
        {
           "system":"http://loinc.org",
           "code":"72831-1",
           "display":"US.doppler Extremity arteries - bilateral for physiologic artery study limited"
        }
     ]
  },
```

Thank you, Regards

**Comment by okeefm** [comment]
Hello @JuliusSkrisa! Thanks for reaching out to us. Are you able to provide the FHIR JSON and upload settings that were causing this issue? That should help us figure out what the root issue is. Thank you!

**Comment by JuliusSkrisa** [comment]
@okeefm thanks for quick response,

I have created minimal fhir json file where the error occurs, all settings of validation are default.

`{
    "resourceType": "Bundle",
    "id": "101",
    "type": "collection",
    "entry": [
        {
            "fullUrl": "urn:uuid:aec29600-4f34-11eb-ae93-0242ac130002",
            "resource": {
                "resourceType": "Observation",
                "id": "right",
                "status": "final",
                "code": {
                    "coding": [
                        {
                            "system": "http://loinc.org",
                            "code": "72831-1",
                            "display": "US.doppler Extremity arteries - bilateral for physiologic artery study limited"
                        }
                    ]
                }
            }
        }
    ]
}`

**Comment by okeefm** [comment]
Hello @JuliusSkrisa!

Thanks for providing this minimal example! I did some investigation, and it appears there was a transient error in our validation system. After restarting the system on our server, this error seems to have fixed itself. Please feel free to reach out again or re-open this ticket if you find this error again!

Thank you,
Michael
